Algoritmo "semnome"

Var
idade: inteiro,


Inicio
escreval ("digite sua idade: ")
leia (idade)
se ((idade >=18) e (idade<=65)) entao
escreval ("SEU VOTO É OBRIGATÓRIO")
senao

se idade >65 entao

escreval ("seu voto é opcional")
senao

se ((idade>=16) e  (idade <18)) entao
escreval ("seu voto é opcional")
senao
escreval ("voce nao pode votar")

fimse

fimse

fimse


Fimalgoritmo